<?php

$flash = $this->flashMessenger();

$flash->setMessageOpenFormat(
    '<div%s>
        <button type="button" class="close" data-dismiss="alert" aria-hidden="true">
                &times;
        </button>
        
        <ul class="list-unstyled">
    <li>'
)->setMessageSeparatorString('</li><li>')->setMessageCloseString('</li></ul></div>');

echo $flash->render('info', ['alert quizAlert', 'alert-dismissible', 'alert-info']);
echo $flash->render('error', ['alert quizAlert', 'alert-dismissible', 'alert-danger']);
echo $flash->render('default', ['alert quizAlert', 'alert-dismissible', 'alert-warning']);
echo $flash->render('success', ['alert quizAlert', 'alert-dismissible', 'alert-success']);