version: "3"

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: "db"
      POSTGRES_PASSWORD: ""
      POSTGRES_HOST_AUTH_METHOD: "trust"
    ports:
      - "5432:5432"
    volumes:
      - ./:/var/www/html

  app:
    image: allanrodriguesmachado/webserver:1.0
    volumes:
      - ./:/var/www/html
    ports:
      - "8000:80"
    links:
      - db
    depends_on:
      - db
    tty: true